# Generated by Django 5.2.15 on 2026-07-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auditorialog_hash_auditorialog_previous_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorialog',
            name='mitre_tactic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auditorialog',
            name='mitre_technique',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
